name: The Hitchhiker's Guide to Compression
title: The Hitchhiker's Guide to Compression
description: A collection of resources and posts to help people understand compression algorithms.
footer-links:
  github: go-compression/go-compression.github.io
# url: https://go-compression.github.io/

url: "" # blank in development

development: true # optional, you can use in liquid tag conditionals

exclude: [node_modules, gulpfile.js]

sass:
  sass_dir: _sass

source: site

readme_index:
  enabled: false

# remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/go-compression/go-compression.github.io"
