name: The Hitchhiker's Guide to Compression
title: The Hitchhiker's Guide to Compression
description: A collection of resources and posts to help people understand compression algorithms.
url: https://go-compression.github.io/

exclude: [node_modules, gulpfile.js]

readme_index:
  enabled: false

remote_theme: pmarsceill/just-the-docs
